name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup dependencies
        run: sudo apt-get install make clang-format
      - name: Run make ci target
        run: make ci
