extern	char	*strncpy(char *, const char *, int32);
extern	char	*strncat(char *, const char *, int32);
extern	int32	strncmp(const char *, const char *, int32);
extern	char	*strchr(const char *, int32);
extern	char	*strrchr(const char *, int32);
extern	char	*strstr(const char *, const char *);
extern	int32	strnlen(const char *, uint32);
extern	int	strlen(const char *str);
extern int strspn(const char *s1,const char *s2);
extern int strcspn(const char *string,const char *reject);
extern int	strcpy(char		*,const char		*);
extern int	strcmp(char		*,char		*);
extern char *strtok(char *, const char *);
extern char *strcat(char *dest, const char *src);
extern int memcmp(const void *, const void *, int);
extern void *memcpy(void *, const void *, int);
extern void *memchr(const void *, int, int);
extern void *memset(void *, int, int);
extern void *memmove(void *dst, const void *src, size_t len);